// This file is computer-generated by onnx2c 
// Command Line: ./onnx2c baldor_gradnet.onnx

// onnx2c
// Git Branch: master
// Git Commit: bfd0753

// ONNX Model
// Produced By: pytorch, version 2.9.0+cpu
// ONNX IR version: 18

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const float tensor_model_A[12][2] = 
{
  {-0.04639985039830207825f, 0.00000002232143359038f},
  {-0.04070812091231346130f, 0.00000659628494759090f},
  {0.04627880826592445374f, -0.00000042147803469561f},
  {-1.31287610530853271484f, -0.41103422641754150391f},
  {-1.02402436733245849609f, 0.24409246444702148438f},
  {0.04425299167633056641f, 0.00000924484902498079f},
  {-0.04658152163028717041f, 0.00000001893151235777f},
  {-0.25765353441238403320f, -1.20074820518493652344f},
  {0.38721328973770141602f, 0.22823473811149597168f},
  {-0.48493421077728271484f, -0.16998460888862609863f},
  {0.02380533516407012939f, -0.00000000964297619532f},
  {0.07080256193876266479f, -0.00000006638830996053f}
};
static const float tensor_model_b[12] = 
{-0.39921689033508300781f, -0.77714323997497558594f, 0.67201489210128784180f, 1.12515163421630859375f, -0.05160859599709510803f, -0.14440332353115081787f, -0.65690332651138305664f, 1.21523845195770263672f, -0.13614024221897125244f, -0.17448049783706665039f, -0.08643583953380584717f, -0.20272244513034820557f};
static const float tensor_model_b0[2] = 
{0.09869614243507385254f, 0.00000000000000000000f};
static const float tensor_model_C[2][2] = 
{
  {1.00000000000000000000f, 0.00000000000000000000f},
  {0.00000000000000000000f, -1.00000000000000000000f}
};
static const float tensor_permute[2][12] = 
{
  {-0.04639985039830207825f, -0.04070812091231346130f, 0.04627880826592445374f, -1.31287610530853271484f, -1.02402436733245849609f, 0.04425299167633056641f, -0.04658152163028717041f, -0.25765353441238403320f, 0.38721328973770141602f, -0.48493421077728271484f, 0.02380533516407012939f, 0.07080256193876266479f},
  {0.00000002232143359038f, 0.00000659628494759090f, -0.00000042147803469561f, -0.41103422641754150391f, 0.24409246444702148438f, 0.00000924484902498079f, 0.00000001893151235777f, -1.20074820518493652344f, 0.22823473811149597168f, -0.16998460888862609863f, -0.00000000964297619532f, -0.00000006638830996053f}
};
static const float tensor_where[2][2] = 
{
  {0.01501083932816982269f, 0.00000000000000000000f},
  {0.00000000000000000000f, 0.00291348551400005817f}
};
static const float tensor_exp_1[1] = 
{0.07304058969020843506f};
static const float tensor_val_0 = 
1.31256651878356933594f;
static const float tensor_val_16 = 
2.00000000000000000000f;
static const float tensor_val_28 = 
0.50000000000000000000f;
static const float tensor_val_29 = 
26.00000000000000000000f;
union tensor_union_0 {
float tensor_div[1][2];
float tensor_matmul_4[1][12];
float tensor_matmul_5[1][2];
float tensor_pow_2[1][12];
float tensor_sqrt_1[1][12];
float tensor_matmul_6[1][2];
float tensor_matmul_7[1][2];
float tensor_mul[1][2];
};
static union tensor_union_0 tu0;

union tensor_union_1 {
float tensor_matmul[1][12];
float tensor_matmul_1[1][2];
float tensor_pow_1[1][12];
float tensor_sqrt[1][12];
float tensor_matmul_2[1][2];
float tensor_matmul_3[1][2];
float tensor_add_5[1][2];
float tensor_add_8[1][2];
};
static union tensor_union_1 tu1;

union tensor_union_2 {
float tensor_add[1][12];
float tensor_add_3[1][2];
};
static union tensor_union_2 tu2;

union tensor_union_3 {
float tensor_add_1[1][2];
float tensor_add_4[1][12];
float tensor_add_7[1][2];
};
static union tensor_union_3 tu3;

union tensor_union_4 {
float tensor_add_2[1][12];
float tensor_div_1[1][12];
float tensor_add_6[1][12];
float tensor_div_2[1][12];
};
static union tensor_union_4 tu4;


/*
 * Operand:           Div
 * Name in ONNX file: node_div
 */
FUNC_PREFIX void node_node_div( const float A[1][2], const float *B, float C[1][2] )
{
	/* Div
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]/ *B;;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul
 */
FUNC_PREFIX void node_node_matmul( const float A[1][2], const float B[2][12], float Y[1][12] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 12; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add
 */
FUNC_PREFIX void node_node_add( const float A[1][12], const float B[12], float C[1][12] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]+B[i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_1
 */
FUNC_PREFIX void node_node_matmul_1( const float A[1][2], const float B[2][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_1
 */
FUNC_PREFIX void node_node_add_1( const float A[1][2], const float B[2], float C[1][2] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]+B[i1];;
	}
}

/*
 * Operand:           Pow
 * Name in ONNX file: node_pow_1
 */
FUNC_PREFIX void node_node_pow_1( const float A[1][12], const float *B, float C[1][12] )
{
	/* Pow
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = powf(A[0][i1],*B);;
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_2
 */
FUNC_PREFIX void node_node_add_2( const float A[1][12], const float B[1], float C[1][12] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]+B[0];;
	}
}

/*
 * Operand:           Sqrt
 * Name in ONNX file: node_sqrt
 */
FUNC_PREFIX void node_node_sqrt( const float X[1][12], float Y[1][12] )
{
	/* Sqrt
	   Implemented with Elementwise template.
	   alpha = 0.00000000000000000000
	   beta = 0.00000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<12; i1++) {
		Y[i0][i1] = sqrtf(X[i0][i1]);
	}
	}
}

/*
 * Operand:           Div
 * Name in ONNX file: node_div_1
 */
FUNC_PREFIX void node_node_div_1( const float A[1][12], const float B[1][12], float C[1][12] )
{
	/* Div
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]/ B[0][i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_2
 */
FUNC_PREFIX void node_node_matmul_2( const float A[1][12], const float B[12][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 12; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_3
 */
FUNC_PREFIX void node_node_add_3( const float A[1][2], const float B[1][2], float C[1][2] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]+B[0][i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_3
 */
FUNC_PREFIX void node_node_matmul_3( const float A[1][2], const float B[2][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_4
 */
FUNC_PREFIX void node_node_matmul_4( const float A[1][2], const float B[2][12], float Y[1][12] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 12; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_4
 */
FUNC_PREFIX void node_node_add_4( const float A[1][12], const float B[12], float C[1][12] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]+B[i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_5
 */
FUNC_PREFIX void node_node_matmul_5( const float A[1][2], const float B[2][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_5
 */
FUNC_PREFIX void node_node_add_5( const float A[1][2], const float B[2], float C[1][2] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]+B[i1];;
	}
}

/*
 * Operand:           Pow
 * Name in ONNX file: node_pow_2
 */
FUNC_PREFIX void node_node_pow_2( const float A[1][12], const float *B, float C[1][12] )
{
	/* Pow
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = powf(A[0][i1],*B);;
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_6
 */
FUNC_PREFIX void node_node_add_6( const float A[1][12], const float B[1], float C[1][12] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]+B[0];;
	}
}

/*
 * Operand:           Sqrt
 * Name in ONNX file: node_sqrt_1
 */
FUNC_PREFIX void node_node_sqrt_1( const float X[1][12], float Y[1][12] )
{
	/* Sqrt
	   Implemented with Elementwise template.
	   alpha = 0.00000000000000000000
	   beta = 0.00000000000000000000
	*/
	for (unsigned i0=0; i0<1; i0++) {
	for (unsigned i1=0; i1<12; i1++) {
		Y[i0][i1] = sqrtf(X[i0][i1]);
	}
	}
}

/*
 * Operand:           Div
 * Name in ONNX file: node_div_2
 */
FUNC_PREFIX void node_node_div_2( const float A[1][12], const float B[1][12], float C[1][12] )
{
	/* Div
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<12; i1++)
	{
		C[0][i1] = A[0][i1]/ B[0][i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_6
 */
FUNC_PREFIX void node_node_matmul_6( const float A[1][12], const float B[12][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 12; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_7
 */
FUNC_PREFIX void node_node_add_7( const float A[1][2], const float B[1][2], float C[1][2] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]+B[0][i1];;
	}
}

/*
 * Operand:           MatMul
 * Name in ONNX file: node_matmul_7
 */
FUNC_PREFIX void node_node_matmul_7( const float A[1][2], const float B[2][2], float Y[1][2] )
{
	/* MatMul (AbstractMatMul) */
	{
		for (unsigned i = 0; i < 1; i++)
		for (unsigned j = 0; j < 2; j++)
		{
			Y[i][j] = 0;
			for (unsigned k = 0; k < 2; k++)
			{
				Y[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/*
 * Operand:           Add
 * Name in ONNX file: node_add_8
 */
FUNC_PREFIX void node_node_add_8( const float A[1][2], const float B[1][2], float C[1][2] )
{
	/* Add
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]+B[0][i1];;
	}
}

/*
 * Operand:           Mul
 * Name in ONNX file: node_mul
 */
FUNC_PREFIX void node_node_mul( const float A[1][2], const float *B, float C[1][2] )
{
	/* Mul
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]**B;;
	}
}

/*
 * Operand:           Mul
 * Name in ONNX file: node_mul_1
 */
FUNC_PREFIX void node_node_mul_1( const float A[1][2], const float *B, float C[1][2] )
{
	/* Mul
	   Implemented with Elementwise_2 template.
	   Attributes (these are the union of attributes for all 2-element-wise
	               operands. So most likely these values are ignored by onnx2c).
	   shift_dir: NOT_GIVEN
	   fmod: 0
	 */
	for (unsigned i0=0; i0<1; i0++)
	for (unsigned i1=0; i1<2; i1++)
	{
		C[0][i1] = A[0][i1]**B;;
	}
}

extern "C" {
	void entry(const float tensor_flux_input[1][2], float tensor_current_output[1][2]){
		node_node_div( tensor_flux_input, &tensor_val_0, tu0.tensor_div);
		node_node_matmul( tu0.tensor_div, tensor_permute, tu1.tensor_matmul);
		node_node_add( tu1.tensor_matmul, tensor_model_b, tu2.tensor_add);
		node_node_matmul_1( tu0.tensor_div, tensor_where, tu1.tensor_matmul_1);
		node_node_add_1( tu1.tensor_matmul_1, tensor_model_b0, tu3.tensor_add_1);
		node_node_pow_1( tu2.tensor_add, &tensor_val_16, tu1.tensor_pow_1);
		node_node_add_2( tu1.tensor_pow_1, tensor_exp_1, tu4.tensor_add_2);
		node_node_sqrt( tu4.tensor_add_2, tu1.tensor_sqrt);
		node_node_div_1( tu2.tensor_add, tu1.tensor_sqrt, tu4.tensor_div_1);
		node_node_matmul_2( tu4.tensor_div_1, tensor_model_A, tu1.tensor_matmul_2);
		node_node_add_3( tu3.tensor_add_1, tu1.tensor_matmul_2, tu2.tensor_add_3);
		node_node_matmul_3( tu0.tensor_div, tensor_model_C, tu1.tensor_matmul_3);
		node_node_matmul_4( tu1.tensor_matmul_3, tensor_permute, tu0.tensor_matmul_4);
		node_node_add_4( tu0.tensor_matmul_4, tensor_model_b, tu3.tensor_add_4);
		node_node_matmul_5( tu1.tensor_matmul_3, tensor_where, tu0.tensor_matmul_5);
		node_node_add_5( tu0.tensor_matmul_5, tensor_model_b0, tu1.tensor_add_5);
		node_node_pow_2( tu3.tensor_add_4, &tensor_val_16, tu0.tensor_pow_2);
		node_node_add_6( tu0.tensor_pow_2, tensor_exp_1, tu4.tensor_add_6);
		node_node_sqrt_1( tu4.tensor_add_6, tu0.tensor_sqrt_1);
		node_node_div_2( tu3.tensor_add_4, tu0.tensor_sqrt_1, tu4.tensor_div_2);
		node_node_matmul_6( tu4.tensor_div_2, tensor_model_A, tu0.tensor_matmul_6);
		node_node_add_7( tu1.tensor_add_5, tu0.tensor_matmul_6, tu3.tensor_add_7);
		node_node_matmul_7( tu3.tensor_add_7, tensor_model_C, tu0.tensor_matmul_7);
		node_node_add_8( tu2.tensor_add_3, tu0.tensor_matmul_7, tu1.tensor_add_8);
		node_node_mul( tu1.tensor_add_8, &tensor_val_28, tu0.tensor_mul);
		node_node_mul_1( tu0.tensor_mul, &tensor_val_29, tensor_current_output);
	}
}